### ISSUE TITLE
Can not produce reasonable results

### ISSUE THREAD

**Issue by Adenialzz** [snap-research/weights2weights#4]
Weights2weights is a great work and thanks for open-sourcing. But when I run the official sampling demo, it can not produce reasonable results. Is something wrong with my understanding or operation?
 
Specifically, I run jupyter notebook `sampling/sampling.ipynb`. I sample a `network` (a LoRA), and use it to generate multiple images. But when I change random seed (keep sampled network unchanged), the generated images are totally not the same person. But I think weights2weights method should guarantee they are consistent person, right ? Is there any mistake with my understanding or operation ?

![image](https://github.com/user-attachments/assets/709c2c8c-4883-4988-a65d-9dbb923e3f24)

![image](https://github.com/user-attachments/assets/95d1d527-0170-49ab-b1c0-1e24eac7c757)

![image](https://github.com/user-attachments/assets/0de32d62-2976-4cf2-a603-ae487c33d6b6)

**Comment by avdravid** [comment]
Thank you for posting your issue. You raise an important point. Models from weights2weights space inherit the limitations of a typical personalized model, specifically issues with generating small faces and not always generating a perfectly consistent identity (i.e. there might be some variations for particular seeds). It looks like the issue you are facing is with the small faces, which is a known issue with Stable Diffusion models. If you take a look at your second image, since it is a small face it only has the coarse features (e.g., beard) of the original identity. 

Here, I sampled a model and generated some images, which are fairly consistent. 
![4](https://github.com/user-attachments/assets/96a0e5d9-ae09-4938-be4d-c8d0fe55afd4)
![5](https://github.com/user-attachments/assets/ffdcd088-96d6-4828-b24b-293a8f9806da)
![1](https://github.com/user-attachments/assets/5acb0862-f7ed-4c58-a462-747f3fd18efd)
![2](https://github.com/user-attachments/assets/ae70420d-3d5b-489b-803d-c54de6adcfc5)

However, the consistency breaks with a more full-body shot. Although it has some similar features, it is hard to tell if it is the exact same person. 
![3](https://github.com/user-attachments/assets/1b0a8222-775e-434a-93d0-5d8f87270b6b)

If you want better consistency, I would suggest sticking to more portrait-style shots where the face is more visible, or if you are interested in full body shots, you will need to find which seeds work well.

**Comment by Adenialzz** [comment]
Got it, thanks.
